Repository DeveloperAcademy-POSTECH/MacC-Team-Vegeting, pull requests merged in 2022-10, with the labels that each got.

#6 [SETTING] 폴더링 & extension 초기설정
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Base.lproj/Main.storyboard
  Vegeting/Global/Base/BaseViewController.swift
  Vegeting/Global/Extensions/NSObject+Extension.swift
  Vegeting/Global/Extensions/UIColor+Extension.swift
  Vegeting/Global/Extensions/UILabel+Extension.swift
  Vegeting/Global/Extensions/UIScreen+Extension.swift
  Vegeting/Global/Extensions/UIStackView+Extention.swift
  Vegeting/Global/Extensions/UIViewController+Extension.swift
  Vegeting/Global/Literals/ImageLiteral.swift
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/Contents.json
  Vegeting/Global/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  Vegeting/Global/Supports/AppDelegate.swift
  Vegeting/Global/Supports/Info.plist
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Global/Utils/UIView+Constraint.swift
  Vegeting/Global/Utils/UIViewController+Alert.swift
  Vegeting/SceneDelegate.swift
  Vegeting/Screens/Main/ViewController.swift
Labels: documentation

#16 [FEAT] 모임개설뷰 폴더링을 진행했습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/Main/ViewController/ViewController.swift
Labels: 🪴 데이크, ⚙️ Setting

#21 [FEAT] GroupCategoryCollectionView 구현
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIView+Extension.swift
  Vegeting/Global/Supports/AppDelegate.swift
  Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
  Vegeting/Global/UIComponent/GroupCategoryView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
Labels: 🪴 데이크, 🖼 UI

#26 [FEATURE]: 모임, 채팅, 유저에대한 전체 서버모델 생성
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Models/Chat.swift
  Vegeting/Global/Models/Club.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Models/VFUser.swift
  Vegeting/Global/Supports/GoogleService-Info.plist
Labels: 🪴 닐, 🌏서버 아키텍쳐

#50 [FEAT] APIKey 핸들링위한 xcconfig파일 추가
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/Supports/Info.plist
  Vegeting/Global/Supports/Secret.xcconfig
Labels: 🪴 데이크, ⚙️ Setting

#30 [FEAT]: PostDetailView 내부 coverImageView 생성
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/xcuserdata/kim-wonhui.xcuserdatad/xcschemes/xcschememanagement.plist
  Vegeting/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/coverImage.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/coverImage.imageset/backgroundImage.jpg
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
Labels: 🪴 메이, 🖼 UI

#27 [FEAT]: DatePicker와 인원수 collectionView를 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/Date+Extension.swift
  Vegeting/Global/Extensions/String+Extension.swift
  Vegeting/Global/Extensions/UIView+Extension.swift
  Vegeting/Screens/CreateGroup/Cells/NumberOfPeopleCollectionViewCell.swift
  Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
Labels: 🪴 데이크, 🖼 UI

#36 [FEAT]: createGatheringSecondView 구현 (#29)
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/xcshareddata/xcschemes/Vegeting.xcscheme
  Vegeting/Global/Base/BaseViewController.swift
  Vegeting/Global/Extensions/UIColor+Extension.swift
  Vegeting/Global/Extensions/UIStackView+Extention.swift
  Vegeting/Global/Extensions/UITextField+Extension.swift
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/UIComponent/GroupInfoView.swift
  Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
Labels: 🪴 제로, 🖼 UI

#46 [FEAT]: 글로벌 바텀 버튼 생성
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIButton+Extension.swift
  Vegeting/Global/Extensions/UIStackView+Extention.swift
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Global/UIComponent/BottomButton.swift
  Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
Labels: 🪴 제로, 🖼 UI
