Repository DeveloperAcademy-POSTECH/MacC-Team-Vegeting, pull requests merged in 2022-12, with the labels that each got.

#177 [FEAT]: 메인뷰(모임콜렉션뷰)에 캐러셀, 필터링 기능 추가
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
  Vegeting/Global/UIComponent/GroupCategoryView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
  Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
Labels: 🖼 UI, ⭐️ Logic

#165 [FEAT]: SecondCreateGroupView에 데이터를 전달하고 hi-fi를 적용하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UITextField+Extension.swift
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/UIComponent/GroupInfoView.swift
  Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
Labels: 🪴 데이크, 🖼 UI, ⭐️ Logic

#184 [FEAT]: 모임에 참여하기 기능을 위한 함수 구현
  .gitignore
  Vegeting/Global/Extensions/UIImageView+Extension.swift
  Vegeting/Global/Literals/ErrorLiteral.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Models/Chat.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Models/RecentChat.swift
  Vegeting/Global/Models/VFUser.swift
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
Labels: 🪴 닐, 💽파이어베이스

#222 [FEAT] 리드미파일 추가
  README.md
Labels: 🪴 닐, 📝 Docs
