Repository DeveloperAcademy-POSTECH/MacC-Team-Vegeting, pull requests merged in 2022-11, with the labels that each got.

#67 [FEAT] PostDetailView 구현 (#66)
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
  Vegeting/Screens/PostDetail/ProfileCollectionViewCell.swift
Labels: 🪴 메이, 🖼 UI

#53 [FEAT]: MainTabBarViewController 구현
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
Labels: 🪴 메이, 🖼 UI

#52 [FEAT]: searchController를 활용하여 지역검색 뷰를 구현하였습니다.
  .gitignore
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/ImageLiteral.swift
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/Models/Address.swift
  Vegeting/Global/Models/Place.swift
  Vegeting/Global/Supports/Secret.xcconfig
  Vegeting/Global/Utils/UINavigationController+Back.swift
  Vegeting/Screens/CreateGroup/Cells/NumberOfPeopleCollectionViewCell.swift
  Vegeting/Screens/CreateGroup/Cells/SearchedAddressTableViewCell.swift
  Vegeting/Screens/CreateGroup/Components/EmptyResultView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
  Vegeting/Screens/Main/ViewController/ViewController.swift
Labels: 🪴 데이크, ⭐️ Feature

#56 [FEAT]: 모집중인 클럽을 보여주는 collectionView
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIView+Extension.swift
  Vegeting/Global/Models/Club.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/UIComponent/LabelWithImageStackView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
Labels: 🪴 제로, 🖼 UI

#57 [FEAT]: 모임생성뷰의 플로우를 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/UIComponent/GroupCategoryView.swift
  Vegeting/Screens/CreateGroup/Components/EmptyResultView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
Labels: 🪴 데이크, ⭐️ Logic

#55 [FEAT]: 파이어베이스 게시물, 채팅 CRU
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/MockData.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Models/Chat.swift
  Vegeting/Global/Models/Club.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Models/VFUser.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/Main/ViewController/ViewController.swift
  Vegeting/Screens/SignIn/ViewModel/SignInViewModel.swift
Labels: 🪴 닐

#61 [FEAT]: 채팅방 관련 Server 함수
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Models/Chat.swift
Labels: 🪴 닐, 🌏서버 아키텍쳐

#82 [FEAT]: 이슈 및 pr 템플릿 수정 (#81)
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug-report.md
Labels: 🪴 메이, ⚙️ Setting

#93 [FEAT] 지역검색시 검색 결과가 없는 경우 검색어 추천 기능 구현
  Vegeting/Screens/CreateGroup/Cells/SearchedAddressTableViewCell.swift
  Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
Labels: ⭐️ Logic

#94 [FEAT]: 채팅방을 보여주는 뷰를 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/Date+Extension.swift
  Vegeting/Global/Extensions/UIStackView+Extention.swift
  Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
  Vegeting/Screens/ChatRoom/ViewController/ChatRoomListViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
Labels: 🪴 데이크, 🖼 UI, ⭐️ Logic

#87 [FEAT]: 애플 로그인 추가
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/xcuserdata/kim-wonhui.xcuserdatad/xcschemes/xcschememanagement.plist
  Vegeting/Global/Manager/AuthManager.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Supports/GoogleService-Info.plist
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/SignIn/ViewControllers/SignInViewController.swift
  Vegeting/Screens/SignIn/ViewModel/SignInViewModel.swift
  Vegeting/Vegeting.entitlements
Labels: 🪴 닐

#97 [FEAT]: 모임글 리스트 뷰 커스텀 네비바, 세그먼트컨트롤 구현
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIColor+Extension.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Global/UIComponent/LabelWithImageStackView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
Labels: 🪴 제로, 🖼 UI

#98 [FEAT]: 글로벌 카테고리뷰
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/MockData.swift
  Vegeting/Global/Models/Club.swift
  Vegeting/Global/Models/Participant.swift
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage1.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage1.imageset/groupCoverImage1.jpeg
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage2.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage2.imageset/groupCoverImage2.jpeg
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage3.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/groupCoverImage3.imageset/groupCoverImage3.jpeg
  Vegeting/Global/UIComponent/CategoryView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
Labels: 🪴 제로, 🖼 UI

#95 [FEAT]: 채팅방에서 보여줄 profile halfModal을 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Resources/Assets.xcassets/verticalEllipsis.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/verticalEllipsis.imageset/verticalEllipsis.png
  Vegeting/Global/UIComponent/ProfileView.swift
  Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
  Vegeting/Screens/ChatRoom/UIComponent/InterestView.swift
  Vegeting/Screens/ChatRoom/ViewController/ChatRoomListViewController.swift
  Vegeting/Screens/ChatRoom/ViewController/ProfileHalfModalViewController.swift
  Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
Labels: 🪴 데이크, 🖼 UI

#104 [FEAT]: MyPage뷰를 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIColor+Extension.swift
  Vegeting/Global/Models/MyPageSettingElement.swift
  Vegeting/Global/UIComponent/BottomButton.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
  Vegeting/Screens/MyPage/Cell/MyPageProfileTableViewCell.swift
  Vegeting/Screens/MyPage/Cell/MyPageTableViewCell.swift
  Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyProfileEditViewController.swift
Labels: 🪴 데이크, 🖼 UI

#99 [FEAT]: 프로필 설정 중 프로필 사진과 닉네임 설정 뷰 구현
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/xcuserdata/kim-wonhui.xcuserdatad/xcschemes/xcschememanagement.plist
  Vegeting/Global/Resources/Assets.xcassets/progress1.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/progress1.imageset/progress1.jpg
  Vegeting/Global/Resources/Assets.xcassets/progress2.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/progress2.imageset/progress2.jpg
  Vegeting/Global/Resources/Assets.xcassets/progress3.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/progress3.imageset/progress3.jpg
  Vegeting/Global/Resources/Assets.xcassets/progress4.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/progress4.imageset/progress4.jpg
  Vegeting/Global/Resources/Assets.xcassets/progress5.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/progress5.imageset/progress5.jpg
  Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
Labels: 🪴 메이, 🖼 UI

#100 [FEAT]: 카카오 로그인 구현
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Manager/AuthManager.swift
  Vegeting/Global/Supports/AppDelegate.swift
  Vegeting/Global/Supports/Info.plist
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Screens/SignIn/ViewControllers/SignInViewController.swift
  Vegeting/Screens/SignIn/ViewModel/SignInViewModel.swift
Labels: 🪴 닐, 💽파이어베이스

#102 [FEAT]: 채팅방 목록에 띄울 최근에 보낸 메세지 데이터 연동
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/ErrorLiteral.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Models/RecentChat.swift
Labels: 🪴 닐, 💽파이어베이스

#115 [FEAT]: 위치 인증 화면을 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Screens/RegisterUserProfile/Component/MapView.swift
  Vegeting/Screens/RegisterUserProfile/LocationAuthViewController.swift
Labels: 🪴 메이, 🖼 UI

#108 [FEAT]: 채팅방 UI 1,2번 task 작업
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Screens/ChatRoomDetail/Component/ChatRoomContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/ViewController/ChatRoomViewController.swift
Labels: 🪴 닐, 🖼 UI

#110 [FIX]: CollectionView ReusableCell 문제 해결
  Vegeting/Screens/ChatRoomDetail/Component/ChatRoomContentCollectionViewCell.swift
Labels: 🐜 Bugfix, 🪴 닐

#124 [FEAT]: recentChat firebase 데이터와 ChatRoomList UI를 연결했습니다.
  Vegeting/Screens/ChatRoom/ViewController/ChatRoomListViewController.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
Labels: 🪴 데이크, ⭐️ Logic

#121 [FEAT]: 프로필 설정 중 성별, 출생년도 설정 UI를 구현합니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Screens/ChatRoom/ViewController/ChatRoomListViewController.swift
  Vegeting/Screens/RegisterUserProfile/UserGenderBirthViewController.swift
Labels: 🪴 메이, 🖼 UI

#113 [FEAT]: 채팅방 UI 기초 구현 완료(내가 보낸 메세지, 남이 보낸 메세지)
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Screens/ChatRoomDetail/Component/ChatRoomContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/Component/MyChatContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/Component/OtherChatContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/ViewController/ChatRoomViewController.swift
  Vegeting/Screens/ChatRoomDetail/ViewModel/ChatRoomViewModel.swift
Labels: 🪴 닐, 🛠 Refactor, 🖼 UI

#133 [FEAT]: UserProfileView 보충(추가) 사항을 구현합니다.
  Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
Labels: 🪴 메이, 🖼 UI

#137 [FEAT]: tab bar에 hi-fi 디자인을 적용하였습니다.
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/Union.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/Union.imageset/Union.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/calendarFill.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/calendarFill.imageset/calanderFill.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/calendarStroke.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/calendarStroke.imageset/calanderStroke.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/clubFill.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/clubFill.imageset/clubFill.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/clubStroke.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/clubStroke.imageset/clubStroke.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/mypageFill.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/mypageFill.imageset/mypageFill.svg
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/mypageStroke.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/tabbarImage/mypageStroke.imageset/mypageStroke.svg
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
Labels: 🪴 데이크, 🖼 UI

#125 [FEAT]: 마이프로필의 데이터를 firebase에서 받아옵니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/Int+Extension.swift
  Vegeting/Global/Models/VFUser.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyProfileEditViewController.swift
Labels: 🪴 데이크, ⭐️ Logic

#129 [FEAT]: 파이어베이스에서 모든 클럽, 가입한 클럽을 불러와 띄워주기
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Resources/Assets.xcassets/emptyImage.imageset/Contents.json
  Vegeting/Global/Resources/Assets.xcassets/emptyImage.imageset/emptyImage.png
  Vegeting/Global/Supports/SceneDelegate.swift
  Vegeting/Global/UIComponent/CategoryView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyClubsViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
  Vegeting/Screens/MyPage/ViewController/MyProfileEditViewController.swift
Labels: 🪴 제로, 📬 API, 💽파이어베이스

#134 [FEAT]: 채팅방에서 메세지 필요 로직 구현(채팅 송신 "나" or "다른 사람", 프로필 유무)
  Vegeting/Global/Extensions/Date+Extension.swift
  Vegeting/Screens/ChatRoomDetail/Component/MyChatContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/Component/OtherChatContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/ViewController/ChatRoomViewController.swift
  Vegeting/Screens/ChatRoomDetail/ViewModel/ChatRoomViewModel.swift
  Vegeting/Screens/SignIn/ViewControllers/SignInViewController.swift
Labels: 🪴 닐, ⭐️ Logic, 💽파이어베이스

#139 [FEAT]: 파이어베이스에 이미지 파일을 업로드하고 다운로드 하는 api를 작성합니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIImage+Extension.swift
  Vegeting/Global/Manager/FirebaseStorageManager.swift
Labels: 🪴 제로, 📬 API, 💽파이어베이스

#156 [FEAT]: 유저 등록할 때 닉네임 중복 체크 로직
  Vegeting/Global/Manager/FirebaseManager.swift
Labels: 🪴 제로, 📬 API, 💽파이어베이스

#143 [FEAT]: 프로필 설정 5번째 뷰를 구현합니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/UIComponent/Cell/InterestCollectionViewCell.swift
  Vegeting/Global/UIComponent/InterestView.swift
  Vegeting/Global/UIComponent/ProfileView.swift
  Vegeting/Screens/ChatRoom/UIComponent/InterestView.swift
  Vegeting/Screens/RegisterUserProfile/UserInterestViewController.swift
Labels: 🪴 데이크, 🖼 UI

#157 [FEAT]: FirstCreateGroupViewController의 SE에서 깨지는 현상 해결 및 hi-fi 적용
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
Labels: 🪴 데이크, 🖼 UI

#141 [FEAT]: 모임글 생성시 선택한 사진도 파베에 저장하기.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/UIImage+Extension.swift
  Vegeting/Global/Literals/ErrorLiteral.swift
  Vegeting/Global/Literals/MockData.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/Manager/FirebaseStorageManager.swift
  Vegeting/Global/Models/Club.swift
  Vegeting/Global/Models/VFUser.swift
  Vegeting/Global/UIComponent/GroupInfoView.swift
  Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
Labels: 🪴 제로, 💽파이어베이스

#148 [FEAT]: 채팅방 구현 완료(CollectionView ScrollToBottom 문제 해결 미흡)
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Extensions/Date+Extension.swift
  Vegeting/Screens/ChatRoomDetail/Component/MessageDateCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/Component/OtherChatContentCollectionViewCell.swift
  Vegeting/Screens/ChatRoomDetail/ViewController/ChatRoomViewController.swift
  Vegeting/Screens/ChatRoomDetail/ViewModel/ChatRoomViewModel.swift
Labels: 🪴 닐, 🖼 UI

#158 [FEAT]: 클럽 커버 이미지를 불러와 보여줍니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vegeting/Global/Extensions/UIImageView+Extension.swift
  Vegeting/Global/Manager/FirebaseStorageManager.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
Labels: 🪴 제로, 🖼 UI, 💽파이어베이스

#144 [FEAT]: 신고, 차단, 탈퇴 뷰를 구현하였습니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting/Global/Literals/StringLiteral.swift
  Vegeting/Global/Utils/UIViewController+Alert.swift
  Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
  Vegeting/Screens/Report/Cell/ReportTableViewCell.swift
  Vegeting/Screens/Report/Component/ReportTableViewHeaderView.swift
  Vegeting/Screens/Report/ViewController/ReportViewController.swift
Labels: 🪴 데이크, 🖼 UI

#176 [FEAT]: 마감된 모임은 마지막에 보여주도록 api 수정
  Vegeting/Global/Manager/FirebaseManager.swift
Labels: 🪴 제로, 📬 API

#159 [FEAT]: 모임글 상세화면에 해당 모임 정보를 띄워줍니다.
  Vegeting/Global/Extensions/UIImageView+Extension.swift
  Vegeting/Global/UIComponent/BottomButton.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
Labels: 🪴 제로, 🖼 UI

#146 [FEAT]: 프로필 설정 페이지 중 채식 단계를 선택하고 한 줄 소개를 작성하는 페이지를 구현합니다.
  Vegeting.xcodeproj/project.pbxproj
  Vegeting.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vegeting/Global/Models/VegetarianTypeDescription.swift
  Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/LocationAuthViewController.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/SelectVegetarianTypeViewController.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/UserGenderBirthViewController.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/UserInterestViewController.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/UserProfileViewController.swift
  Vegeting/Screens/RegisterUserProfile/ViewController/UserTypeIntroductionViewController.swift
Labels: 🪴 메이, 🖼 UI

#164 [FEAT]: PostDetailViewController에 들어갈 때 내가 작성한 글인지 구분하여 button, actionSheet에 변화를 줍니다.
  Vegeting.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vegeting/Global/Literals/ErrorLiteral.swift
  Vegeting/Global/Manager/AuthManager.swift
  Vegeting/Global/Manager/FirebaseManager.swift
  Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
  Vegeting/Global/UIComponent/GroupCategoryView.swift
  Vegeting/Screens/CreateGroup/Cells/NumberOfPeopleCollectionViewCell.swift
  Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
  Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
  Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
  Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
  Vegeting/Screens/Main/ViewController/MainTabBarViewController.swift
  Vegeting/Screens/PostDetail/PostDetailViewController.swift
  Vegeting/Screens/SignIn/ViewModel/SignInViewModel.swift
Labels: 🪴 데이크, 🖼 UI, ⭐️ Logic
